import { CalendarDays, ChevronRight, ShieldCheck } from 'lucide-react'
import { useEffect, useState } from 'react'
import { createAppointment, getDoctors, searchPatients } from '../api'
import Notice from '../components/Notice'

export default function BookingForm() {
  const [doctors, setDoctors] = useState([])
  const [patients, setPatients] = useState([])
  const [form, setForm] = useState({ doctor_id: '', patient_id: '', name: '', phone: '', start_time: '', end_time: '' })
  const [state, setState] = useState({ loading: true, error: '', notice: null })
  const update = (key, value) => setForm(current => ({ ...current, [key]: value }))
  useEffect(() => { getDoctors({ size: 100 }).then(data => setDoctors(data.items)).catch(err => setState({ loading: false, error: err.message })).finally(() => setState(current => ({ ...current, loading: false }))) }, [])
  useEffect(() => { if (!form.name) { setPatients([]); return } const timer = setTimeout(() => searchPatients({ search: form.name, size: 5 }).then(data => setPatients(data.items)).catch(() => {}), 250); return () => clearTimeout(timer) }, [form.name])
  const submit = async event => { event.preventDefault(); setState(current => ({ ...current, notice: null, error: '' })); try { await createAppointment({ doctor_id: Number(form.doctor_id), patient_id: form.patient_id ? Number(form.patient_id) : undefined, patient: form.patient_id ? undefined : { name: form.name, phone: form.phone || undefined }, start_time: new Date(form.start_time).toISOString(), end_time: new Date(form.end_time).toISOString() }); setState(current => ({ ...current, notice: { type: 'success', message: 'Appointment booked successfully.' } })); setForm({ doctor_id: '', patient_id: '', name: '', phone: '', start_time: '', end_time: '' }) } catch (err) { setState(current => ({ ...current, error: err.message })) } }
  if (state.loading) return <div className="loading">Loading doctors…</div>
  return <><header className="topbar"><div><p className="eyebrow">NEW APPOINTMENT</p><h1>Book an appointment</h1></div></header><Notice notice={state.notice || (state.error ? { type: 'error', message: state.error } : null)} onDismiss={() => setState(current => ({ ...current, notice: null, error: '' }))}/><form className="booking-form" onSubmit={submit}><div className="form-intro"><span className="feature-icon yellow"><CalendarDays/></span><div><h2>Find the right time.</h2><p>Every booking is checked against the doctor's live schedule.</p></div></div><div className="form-grid"><label>Doctor<select required value={form.doctor_id} onChange={event => update('doctor_id', event.target.value)}><option value="">Select a doctor</option>{doctors.map(doctor => <option value={doctor.id} key={doctor.id}>{doctor.name} · {doctor.specialty}</option>)}</select></label><label>Patient name<input required value={form.name} onChange={event => { update('name', event.target.value); update('patient_id', '') }} placeholder="e.g. Alia"/>{!form.patient_id && patients.map(patient => <button type="button" className="patient-suggestion" key={patient.id} onClick={() => { setForm(current => ({ ...current, name: patient.name, phone: patient.phone || '', patient_id: String(patient.id) })); setPatients([]) }}>{patient.name} · {patient.phone || 'No phone'}</button>)}</label><label>Phone <span className="optional">optional</span><input value={form.phone} onChange={event => update('phone', event.target.value)}/></label><label>Starts<input required type="datetime-local" value={form.start_time} onChange={event => update('start_time', event.target.value)}/></label><label>Ends<input required type="datetime-local" value={form.end_time} onChange={event => update('end_time', event.target.value)}/></label></div><div className="form-footer"><p><ShieldCheck size={16}/> Double-booking protection is active</p><button className="primary">Confirm appointment <ChevronRight size={18}/></button></div></form></>
}
