import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { CalendarDays, Check, ChevronRight, Clock3, LogIn, LogOut, Menu, Search, ShieldCheck, Sparkles, Stethoscope, UserPlus, X } from 'lucide-react'
import './styles.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000'
const request = async (path, options = {}) => {
  const token = localStorage.getItem('clinicdesk_token')
  const response = await fetch(API + path, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } })
  const body = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(body.detail || 'Something went wrong')
  return body
}
const fmt = value => new Date(value).toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })

function Landing({ onEnter }) {
  return <main className="landing"><nav className="nav"><div className="brand"><span className="brand-mark"><Stethoscope size={18}/></span> ClinicDesk</div><button className="text-button" onClick={onEnter}>Staff sign in <ChevronRight size={16}/></button></nav><section className="hero"><div className="hero-copy"><p className="eyebrow">FRONT DESK, FINALLY IN RHYTHM</p><h1>Appointments that keep the whole clinic moving.</h1><p className="lede">ClinicDesk gives busy care teams one calm place to book, adjust, and find every appointment without the double-booking anxiety.</p><button className="primary" onClick={onEnter}>Open the desk <ChevronRight size={18}/></button><div className="proof"><ShieldCheck size={18}/><span>Database-protected scheduling. Clear cancellation fees.</span></div></div><div className="hero-panel"><div className="panel-top"><span>Today,  Tuesday 18 Jun</span><span className="live"><i/> Live schedule</span></div><div className="hero-appointment"><div className="time">09:30</div><div className="line"/><div><strong>Dr. Maya Chen</strong><span>Jordan Ellis · annual check-in</span></div><Check className="done" size={18}/></div><div className="hero-appointment muted"><div className="time">10:15</div><div className="line"/><div><strong>Open slot</strong><span>Ready to book</span></div><Sparkles className="spark" size={18}/></div><div className="fee-note"><Clock3 size={17}/><span>Cancellation fee logic is handled automatically.</span></div></div></section><section className="feature-strip"><div><span className="feature-icon mint"><ShieldCheck/></span><h3>No double bookings</h3><p>Postgres protects every slot, even when two staff members click at once.</p></div><div><span className="feature-icon coral"><Clock3/></span><h3>Fair cancellation fees</h3><p>Late cancellations are calculated consistently from your clinic policy.</p></div><div><span className="feature-icon yellow"><Search/></span><h3>Find patients fast</h3><p>Search a name and see the full care schedule in a few keystrokes.</p></div></section><section className="coming"><p className="eyebrow">COMING NEXT</p><h2>More calm, on the way.</h2><div className="next-grid"><span>01 <strong>SMS reminders</strong></span><span>02 <strong>Multi-location support</strong></span><span>03 <strong>Waitlist auto-fill</strong></span></div></section></main>
}

function Auth({ onDone }) {
  const [register, setRegister] = useState(false); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState('')
  const submit = async e => { e.preventDefault(); setError(''); try { const data = await request(register ? '/auth/register' : '/auth/login', { method: 'POST', body: JSON.stringify(form) }); localStorage.setItem('clinicdesk_token', data.access_token); onDone() } catch (err) { setError(err.message) } }
  return <main className="auth-page"><div className="auth-aside"><div className="brand"><span className="brand-mark"><Stethoscope size={18}/></span> ClinicDesk</div><div><p className="eyebrow">THE FRONT DESK, REFINED</p><h1>Make room for better conversations.</h1><p>Less time untangling calendars. More time making patients feel looked after.</p></div></div><form className="auth-card" onSubmit={submit}><span className="feature-icon mint">{register ? <UserPlus/> : <LogIn/>}</span><p className="eyebrow">STAFF ACCESS</p><h2>{register ? 'Create your account' : 'Welcome back'}</h2><p className="muted">{register ? 'Set up your clinic desk in a minute.' : 'Sign in to your clinic workspace.'}</p>{register && <label>Full name<input required value={form.name} onChange={e => setForm({...form, name: e.target.value})}/></label>}<label>Email<input required type="email" value={form.email} onChange={e => setForm({...form, email: e.target.value})}/></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={e => setForm({...form, password: e.target.value})}/></label>{error && <div className="error"><X size={16}/>{error}</div>}<button className="primary full">{register ? 'Create account' : 'Sign in'} <ChevronRight size={18}/></button><button type="button" className="link-button" onClick={() => setRegister(!register)}>{register ? 'Already have an account? Sign in' : 'Need an account? Register'}</button></form></main>
}

function App() {
  const [view, setView] = useState(localStorage.getItem('clinicdesk_token') ? 'dashboard' : 'landing'); const [doctors, setDoctors] = useState([]); const [appointments, setAppointments] = useState([]); const [query, setQuery] = useState(''); const [notice, setNotice] = useState('')
  const load = async () => { try { const [docs, appts] = await Promise.all([request('/doctors'), request(`/appointments?size=50${query ? `&patient_name=${encodeURIComponent(query)}` : ''}`)]); setDoctors(docs); setAppointments(appts) } catch (e) { setNotice(e.message) } }
  useEffect(() => { if (view !== 'landing' && view !== 'auth') load() }, [view, query])
  if (view === 'landing') return <Landing onEnter={() => setView('auth')}/>
  if (view === 'auth') return <Auth onDone={() => setView('dashboard')}/>
  const cancel = async id => { try { const result = await request(`/appointments/${id}/cancel`, { method: 'PATCH' }); setNotice(result.late_fee_charged ? `Cancelled. Late fee: $${result.late_fee_amount}` : 'Cancelled with no fee.'); load() } catch (e) { setNotice(e.message) } }
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Stethoscope size={18}/></span> ClinicDesk</div><div className="side-label">WORKSPACE</div><button className={view === 'dashboard' ? 'nav-item active' : 'nav-item'} onClick={() => setView('dashboard')}><CalendarDays size={18}/> Overview</button><button className={view === 'booking' ? 'nav-item active' : 'nav-item'} onClick={() => setView('booking')}><Sparkles size={18}/> Book appointment</button><button className={view === 'schedule' ? 'nav-item active' : 'nav-item'} onClick={() => setView('schedule')}><Clock3 size={18}/> Doctor schedule</button><div className="side-bottom"><button className="nav-item" onClick={() => { localStorage.removeItem('clinicdesk_token'); setView('landing') }}><LogOut size={18}/> Sign out</button></div></aside><section className="workspace"><header className="topbar"><div><p className="eyebrow">TUESDAY, JUNE 18</p><h1>{view === 'dashboard' ? 'Good morning, front desk.' : view === 'booking' ? 'Book an appointment' : 'Doctor schedule'}</h1></div><div className="top-actions"><button className="icon-button"><Menu size={19}/></button><button className="primary small" onClick={() => setView('booking')}>+ New appointment</button></div></header>{notice && <div className="notice"><Check size={17}/>{notice}<button onClick={() => setNotice('')}><X size={16}/></button></div>}{view === 'booking' ? <Booking doctors={doctors} onSaved={() => { setView('dashboard'); load(); setNotice('Appointment booked successfully.') } } onError={setNotice}/> : view === 'schedule' ? <Schedule doctors={doctors} /> : <Dashboard query={query} setQuery={setQuery} appointments={appointments} doctors={doctors} cancel={cancel} />}</section></main>
}

function Dashboard({ query, setQuery, appointments, doctors, cancel }) { return <><div className="stat-grid"><div><span>Appointments today</span><strong>{appointments.length}</strong><small className="up">↑ Schedule is live</small></div><div><span>Open doctors</span><strong>{doctors.length}</strong><small>Ready for bookings</small></div><div><span>Upcoming fees</span><strong>${appointments.filter(a => a.late_fee_charged).reduce((n, a) => n + Number(a.late_fee_amount), 0)}</strong><small>From cancellations</small></div></div><div className="section-heading"><div><p className="eyebrow">APPOINTMENT FINDER</p><h2>What are you looking for?</h2></div><div className="search-box"><Search size={18}/><input placeholder="Search by patient name" value={query} onChange={e => setQuery(e.target.value)}/></div></div><div className="table-wrap"><div className="table-head"><span>Patient</span><span>Doctor</span><span>When</span><span>Status</span><span></span></div>{appointments.length ? appointments.map(a => <div className="table-row" key={a.id}><span><strong>{a.patient_name || `Patient #${a.patient_id}`}</strong><small>Appointment #{a.id}</small></span><span>{a.doctor_name || `Doctor #${a.doctor_id}`}</span><span>{fmt(a.start_time)}<small>{new Date(a.start_time).toLocaleTimeString([], {hour:'numeric', minute:'2-digit'})} – {new Date(a.end_time).toLocaleTimeString([], {hour:'numeric', minute:'2-digit'})}</small></span><span><b className={`status ${a.status}`}>{a.status}</b></span><button className="row-action" disabled={a.status === 'cancelled'} onClick={() => cancel(a.id)}>Cancel</button></div>) : <div className="empty">No appointments match this search.</div>}</div></> }

function Booking({ doctors, onSaved, onError }) { const [form, setForm] = useState({ doctor_id: '', name: '', phone: '', start_time: '', end_time: '' }); const submit = async e => { e.preventDefault(); try { await request('/appointments', { method:'POST', body: JSON.stringify({ doctor_id: Number(form.doctor_id), patient: { name: form.name, phone: form.phone }, start_time: new Date(form.start_time).toISOString(), end_time: new Date(form.end_time).toISOString() }) }); onSaved() } catch (e) { onError(e.message) } }; return <form className="booking-form" onSubmit={submit}><div className="form-intro"><span className="feature-icon yellow"><CalendarDays/></span><div><h2>Find the right time.</h2><p>Every booking is checked against the doctor's live schedule.</p></div></div><div className="form-grid"><label>Doctor<select required value={form.doctor_id} onChange={e => setForm({...form, doctor_id:e.target.value})}><option value="">Select a doctor</option>{doctors.map(d => <option value={d.id} key={d.id}>{d.name} · {d.specialty}</option>)}</select></label><label>Patient name<input required value={form.name} onChange={e => setForm({...form, name:e.target.value})} placeholder="e.g. Jordan Ellis"/></label><label>Phone <span className="optional">optional</span><input value={form.phone} onChange={e => setForm({...form, phone:e.target.value})}/></label><label>Starts<input required type="datetime-local" value={form.start_time} onChange={e => setForm({...form, start_time:e.target.value})}/></label><label>Ends<input required type="datetime-local" value={form.end_time} onChange={e => setForm({...form, end_time:e.target.value})}/></label></div><div className="form-footer"><p><ShieldCheck size={16}/> Double-booking protection is active</p><button className="primary">Confirm appointment <ChevronRight size={18}/></button></div></form> }

function Schedule({ doctors }) { const [doctor, setDoctor] = useState(''); const [day, setDay] = useState(new Date().toISOString().slice(0,10)); const [items, setItems] = useState([]); const load = async () => { if (doctor) setItems(await request(`/doctors/${doctor}/schedule?date=${day}`)) }; useEffect(() => { load() }, [doctor, day]); return <div className="schedule"><div className="schedule-controls"><select value={doctor} onChange={e => setDoctor(e.target.value)}><option value="">Select a doctor</option>{doctors.map(d => <option key={d.id} value={d.id}>{d.name} · {d.specialty}</option>)}</select><input type="date" value={day} onChange={e => setDay(e.target.value)}/></div><div className="timeline">{items.map(a => <div className="timeline-item" key={a.id}><span>{new Date(a.start_time).toLocaleTimeString([], {hour:'numeric', minute:'2-digit'})}</span><div className="timeline-card"><b>Patient #{a.patient_id}</b><small>{fmt(a.start_time)} – {new Date(a.end_time).toLocaleTimeString([], {hour:'numeric', minute:'2-digit'})}</small></div></div>)}{doctor && !items.length && <div className="empty">This doctor has a clear schedule for the selected day.</div>}{!doctor && <div className="empty">Choose a doctor to see their day.</div>}</div></div> }

createRoot(document.getElementById('root')).render(<App />)
